#!/usr/bin/env python3
"""
remove_bloatware.py  —  AlarmApp Bloatware Removal Tool (Android / Windows)
===========================================================================

Analyzes the AlarmApp React Native project and strips out unused dependencies,
the entire iOS directory, dead template code, and other cruft left behind by
the React Native CLI scaffolding.

Usage (Windows):
    python remove_bloatware.py [--dry-run] [path\\to\\AlarmApp]

Flags:
    --dry-run   Show what would be changed without modifying any files.

If no path is given, the current working directory is used.
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path


# ──────────────────────────────────────────────────────────────────
#  Configuration — everything we want to remove lives here so it's
#  easy to audit or extend.
# ──────────────────────────────────────────────────────────────────

# npm packages declared in package.json but never imported in source.
UNUSED_DEPS = [
    "@react-native/new-app-screen",       # default RN welcome screen — unused
    "react-native-safe-area-context",      # declared but never imported
]

# npm devDependencies that are iOS-only and not needed for Android builds.
IOS_ONLY_DEV_DEPS = [
    "@react-native-community/cli-platform-ios",
]

# npm scripts that only apply to iOS.
IOS_ONLY_SCRIPTS = [
    "ios",
]

# Files to delete outright.
FILES_TO_DELETE = [
    "package-lock.json",   # stale lockfile — regenerated by npm install
    "Gemfile",             # Ruby/Bundler — only needed for CocoaPods (iOS)
]

# Directories to delete entirely.
DIRS_TO_DELETE = [
    "ios",                 # entire Xcode / CocoaPods tree — Android only
    ".bundle",             # Ruby bundler config — iOS only
]


# ──────────────────────────────────────────────────────────────────
#  Helpers
# ──────────────────────────────────────────────────────────────────

class Logger:
    """Minimal coloured logger (ANSI codes work in Windows Terminal,
    PowerShell 7+, and VS Code terminal)."""
    GREEN  = "\033[92m"
    YELLOW = "\033[93m"
    RED    = "\033[91m"
    CYAN   = "\033[96m"
    RESET  = "\033[0m"

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.actions: list[str] = []
        # Enable ANSI escape sequences on older Windows consoles
        if sys.platform == "win32":
            os.system("")

    def _prefix(self) -> str:
        return f"{self.YELLOW}[DRY RUN]{self.RESET} " if self.dry_run else ""

    def info(self, msg: str):
        print(f"{self._prefix()}{self.CYAN}i{self.RESET}  {msg}")

    def done(self, msg: str):
        self.actions.append(msg)
        print(f"{self._prefix()}{self.GREEN}+{self.RESET}  {msg}")

    def skip(self, msg: str):
        print(f"{self._prefix()}{self.YELLOW}-{self.RESET}  {msg}")

    def warn(self, msg: str):
        print(f"{self._prefix()}{self.RED}!{self.RESET}  {msg}")

    def summary(self):
        n = len(self.actions)
        word = "would be" if self.dry_run else "were"
        print(f"\n{'='*60}")
        print(f"  {n} change(s) {word} applied.")
        if self.dry_run:
            print(f"  Re-run without --dry-run to apply them.")
        print(f"{'='*60}")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str, log: Logger):
    if not log.dry_run:
        path.write_text(content, encoding="utf-8")


# ──────────────────────────────────────────────────────────────────
#  Step 1 — Remove unused npm dependencies from package.json
# ──────────────────────────────────────────────────────────────────

def clean_package_json(root: Path, log: Logger):
    pkg_path = root / "package.json"
    if not pkg_path.exists():
        log.warn("package.json not found — skipping dependency cleanup.")
        return

    log.info("Scanning package.json for unused & iOS-only dependencies ...")
    pkg = json.loads(read_text(pkg_path))
    removed = []

    # Remove unused dependencies
    for section in ("dependencies", "devDependencies"):
        deps: dict = pkg.get(section, {})
        for name in UNUSED_DEPS:
            if name in deps:
                del deps[name]
                removed.append(f"{name} (from {section})")

    # Remove iOS-only devDependencies
    dev_deps: dict = pkg.get("devDependencies", {})
    for name in IOS_ONLY_DEV_DEPS:
        if name in dev_deps:
            del dev_deps[name]
            removed.append(f"{name} (iOS-only, from devDependencies)")

    # Remove iOS-only scripts
    scripts: dict = pkg.get("scripts", {})
    for name in IOS_ONLY_SCRIPTS:
        if name in scripts:
            del scripts[name]
            removed.append(f"script '{name}' (iOS-only)")

    if removed:
        content = json.dumps(pkg, indent=2) + "\n"
        write_text(pkg_path, content, log)
        for r in removed:
            log.done(f"Removed {r}")
    else:
        log.skip("No unused dependencies found in package.json.")


# ──────────────────────────────────────────────────────────────────
#  Step 2 — Delete unnecessary files and directories
# ──────────────────────────────────────────────────────────────────

def delete_files(root: Path, log: Logger):
    log.info("Checking for files to delete ...")
    for rel in FILES_TO_DELETE:
        target = root / rel
        if target.exists():
            if not log.dry_run:
                target.unlink()
            log.done(f"Deleted {rel}")
        else:
            log.skip(f"{rel} already absent.")


def delete_dirs(root: Path, log: Logger):
    log.info("Checking for directories to delete ...")
    for rel in DIRS_TO_DELETE:
        target = root / rel
        if target.exists() and target.is_dir():
            if not log.dry_run:
                shutil.rmtree(target)
            log.done(f"Deleted {rel}\\ directory")
        else:
            log.skip(f"{rel}\\ already absent.")


# ──────────────────────────────────────────────────────────────────
#  Step 3 — Clean .gitignore (remove iOS / Xcode / CocoaPods entries)
# ──────────────────────────────────────────────────────────────────

def clean_gitignore(root: Path, log: Logger):
    gi_path = root / ".gitignore"
    if not gi_path.exists():
        log.skip(".gitignore not found — skipping.")
        return

    log.info("Cleaning iOS/Xcode/CocoaPods entries from .gitignore ...")
    content = read_text(gi_path)
    lines = content.splitlines()
    cleaned = []
    removed_count = 0

    in_xcode_block = False
    in_ruby_block = False

    for line in lines:
        stripped = line.strip()

        # Detect Xcode block start
        if stripped == "# Xcode":
            in_xcode_block = True
            removed_count += 1
            continue

        # Detect Ruby / CocoaPods block start
        if stripped == "# Ruby / CocoaPods":
            in_ruby_block = True
            removed_count += 1
            continue

        # Inside Xcode block — skip until next section header
        if in_xcode_block:
            if stripped.startswith("# ") and stripped not in ("# Xcode", "#"):
                in_xcode_block = False
                # fall through to keep this line (it's the next section)
            else:
                removed_count += 1
                continue

        # Inside Ruby/CocoaPods block — skip until blank line or next section
        if in_ruby_block:
            if stripped == "" or (stripped.startswith("# ") and stripped != "# Ruby / CocoaPods"):
                in_ruby_block = False
                if stripped == "":
                    continue  # eat the trailing blank line
                # fall through for next section header
            else:
                removed_count += 1
                continue

        cleaned.append(line)

    if removed_count > 0:
        new_content = "\n".join(cleaned).strip() + "\n"
        write_text(gi_path, new_content, log)
        log.done(f"Removed {removed_count} iOS/Xcode/CocoaPods lines from .gitignore")
    else:
        log.skip("No iOS entries found in .gitignore.")


# ──────────────────────────────────────────────────────────────────
#  Step 4 — Verify no dangling imports remain
# ──────────────────────────────────────────────────────────────────

def verify_no_dangling_imports(root: Path, log: Logger):
    """Scan .ts/.tsx/.js/.jsx files for imports of removed packages."""
    log.info("Verifying no source files import removed packages ...")
    problems = []
    for ext in ("*.ts", "*.tsx", "*.js", "*.jsx"):
        for path in root.rglob(ext):
            if "node_modules" in str(path):
                continue
            try:
                src = read_text(path)
            except (UnicodeDecodeError, PermissionError):
                continue
            for pkg in UNUSED_DEPS:
                if pkg in src:
                    problems.append((path.relative_to(root), pkg))

    if problems:
        log.warn("Dangling imports detected — manual cleanup needed:")
        for fpath, pkg in problems:
            log.warn(f"  {fpath} still references '{pkg}'")
    else:
        log.done("No source files reference removed packages.")


# ──────────────────────────────────────────────────────────────────
#  Main
# ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Strip bloatware from the AlarmApp React Native project (Android / Windows).",
    )
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Path to the AlarmApp root directory (default: current dir).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without modifying any files.",
    )
    args = parser.parse_args()

    root = Path(args.project_dir).resolve()
    if not (root / "package.json").exists():
        print(f"Error: {root} does not look like a React Native project "
              f"(no package.json found).", file=sys.stderr)
        sys.exit(1)

    log = Logger(dry_run=args.dry_run)

    print()
    print("============================================================")
    print("       AlarmApp - Bloatware Removal Tool (Android)          ")
    print("============================================================")
    print(f"  Project : {root}")
    print(f"  Mode    : {'DRY RUN' if args.dry_run else 'LIVE'}")
    print()

    clean_package_json(root, log)
    delete_files(root, log)
    delete_dirs(root, log)
    clean_gitignore(root, log)
    verify_no_dangling_imports(root, log)

    log.summary()

    if not args.dry_run:
        print("\n  Next steps:")
        print(f"    1.  cd {root}")
        print( "    2.  npm install          # regenerate a clean lockfile")
        print( "    3.  npm run android      # build & launch on emulator/device")
        print()


if __name__ == "__main__":
    main()